name: Deploy Site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout site
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build the site and deploy
      env:
        RBH_FIREBASE_TOKEN: ${{ secrets.RBH_FIREBASE_TOKEN }}
      run: |
        export FIREBASE_PROJECT="rutherford-nj-beta-site"
        [[ "$GITHUB_REF" == refs/heads/deploy-gh ]] && \
          export FIREBASE_PROJECT="rutherford-nj" && \
          export PREDEPLOY="rm ./_site/robots.txt"
        echo $FIREBASE_PROJECT
        echo $PREDEPLOY
        gem install bundler
        make deploy
