name: Deploy Site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site and deploy
      run: |
        gem install bundler
        make deploy
